version: "3.9"
services:
  nextjs:
    build: .
    container_name: hire_client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/frontend
    command: sh -c "sleep 10 && npm run dev"
